package ch.hegfrederic.presentation;

import ch.hegfrederic.domaine.Commande;
import ch.hegfrederic.domaine.Capsule;
import ch.hegfrederic.domaine.Employe;
import ch.hegfrederic.metier.ListeCapsules;

/**
 * 
 * Enregistrement d'une nouvelle commande pour un employé: Singleton
 * Écran principal
 *
 * @author fredericlopesmagalhaes Numéro du poste: HEG-WS-8468
 * 
 */
public class FrmNouvelleCommande extends java.awt.Frame {

  private static final int DEFAULT_INDEX = 0;
  private static final String 
          MSG_ERREUR = "La valeur saisie doit être un entier > 0",
          LIBELLE_EMPLOYE = "Compléter la commande de ",
          MSG_MONTANT = "Montant de la commande : ";

  private static FrmNouvelleCommande frm;
  private static FrmMain frmMere;
  private static Employe employe;
  private ListeCapsules listeCapsules;

  private FrmNouvelleCommande(FrmMain frmMere, Employe employe){
    initComponents();
    setDonnees(frmMere, employe);
    initMetier();
    initFrame();
  }

  private void setDonnees(FrmMain frmMere, Employe employe){
    this.frmMere = frmMere;
    this.employe = employe;
  }

  private void initMetier() {
    listeCapsules = new ListeCapsules();
  }

  private void fillListCapsules() {
    for (int i = 0, n = listeCapsules.size(); i < n; i++) {
      lstCapsules.add(listeCapsules.get(i).toString());
    }
  }

  private void initFrame() {
    fillListCapsules();
    updateComposants();
  }

  private void updateComposants() {
    lstCapsules.select(DEFAULT_INDEX);
    listeCapsules.setPos(DEFAULT_INDEX);
    lblEmploye.setText(LIBELLE_EMPLOYE + employe.toString());
  }

  public static FrmNouvelleCommande getInstance(FrmMain frmMere, Employe employe) {
    if (frm == null) {
      frm = new FrmNouvelleCommande(frmMere, employe);
    }
    else {
      frm.setDonnees(frmMere, employe);
      frm.updateComposants();
    }
    return frm;
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    lblEmploye = new java.awt.Label();
    lstCapsules = new java.awt.List();
    lblNombre = new java.awt.Label();
    tfNombre = new java.awt.TextField();
    btnEnregistrer = new java.awt.Button();
    lblErreur = new java.awt.Label();

    setTitle("Compléter une commande");
    addWindowListener(new java.awt.event.WindowAdapter() {
      public void windowClosing(java.awt.event.WindowEvent evt) {
        formWindowClosing(evt);
      }
    });

    lblEmploye.setText("Commande pour ...");

    lstCapsules.addItemListener(new java.awt.event.ItemListener() {
      public void itemStateChanged(java.awt.event.ItemEvent evt) {
        changedSelectedCapsule(evt);
      }
    });

    lblNombre.setText("Nombre de capsules");

    tfNombre.addTextListener(new java.awt.event.TextListener() {
      public void textValueChanged(java.awt.event.TextEvent evt) {
        confirmerValeurSaisie(evt);
      }
    });

    btnEnregistrer.setEnabled(false);
    btnEnregistrer.setLabel("Enregistrer la commande");
    btnEnregistrer.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        enregistrerCommande(evt);
      }
    });

    lblErreur.setForeground(java.awt.Color.red);
    lblErreur.setText("La valeur saisie doit être un entier > 0");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addComponent(lstCapsules, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(layout.createSequentialGroup()
                .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
              .addComponent(btnEnregistrer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(lblErreur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
          .addGroup(layout.createSequentialGroup()
            .addComponent(lblEmploye, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 0, Short.MAX_VALUE)))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(lblEmploye, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(2, 2, 2)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(lstCapsules, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(lblErreur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(btnEnregistrer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  /* Fermeture de la fenêtre */
  private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
    frm = null;
    frmMere = null;
    employe = null;
    dispose();
  }//GEN-LAST:event_formWindowClosing

    private void enregistrerCommande(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enregistrerCommande
      Capsule capsule = listeCapsules.getCourant();
      int nombre = Integer.parseInt(tfNombre.getText());
      frmMere.addCommande(new Commande(employe, capsule, nombre));
      frm = null;
      employe = null;
      frmMere = null;
      dispose();
    }//GEN-LAST:event_enregistrerCommande

    private void confirmerValeurSaisie(java.awt.event.TextEvent evt) {//GEN-FIRST:event_confirmerValeurSaisie
      if (ch.hegfrederic.outils.Validation.isIntValid(tfNombre.getText())) {
        double montant = listeCapsules.getCourant().getPrix()*Integer.parseInt(tfNombre.getText());
        lblErreur.setText(MSG_MONTANT + montant);
        btnEnregistrer.setEnabled(true);
      } else {
        lblErreur.setText(MSG_ERREUR);
        btnEnregistrer.setEnabled(false);
      }
      validate();
    }//GEN-LAST:event_confirmerValeurSaisie

  private void changedSelectedCapsule(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_changedSelectedCapsule
    listeCapsules.setPos(lstCapsules.getSelectedIndex());
  }//GEN-LAST:event_changedSelectedCapsule

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private java.awt.Button btnEnregistrer;
  private java.awt.Label lblEmploye;
  private java.awt.Label lblErreur;
  private java.awt.Label lblNombre;
  private java.awt.List lstCapsules;
  private java.awt.TextField tfNombre;
  // End of variables declaration//GEN-END:variables

}
